version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      MEMORY: 3G
      EULA: TRUE
      TZ: Europe/Paris
      DIFFICULTY: normal
      WHITELIST_FILE: ../extra/whitelist.json
      OPS_FILE: ../extra/ops.json
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
    restart: unless-stopped